### ISSUE TITLE
allow to configure random distribution of timer_events

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#15]
It seems that Hindsight randomly distributes when the timer_events of the sandboxes will fire:
https://github.com/trink/hindsight/blob/master/src/hs_sandbox.c#L156-L159

I guess the goal is to better distribute the cpu load but it would be great if it could be configurable.

For example, in my current use case, I'm running tests on an analysis sandbox:
At first I dynamically load a new analysis sandbox which is configured with a ticker_interval of 3s, then inject multiple hindsight messages (through a udp json input sandbox) which should all be received by the tested analysis plugin which emits a single output message (through a udp json output sandbox) and then I check if the output message received is correct.
Because of the random distribution of timer_events, those tests sometimes fails because the multiple input messages that I send through the udp input are not all received in the same timer_event.

So it would be great if we could disable this random distribution of timer_events.

**Comment by bbinet** [comment]
Also it would be great to be able to synchronize sandboxes timer_events across Hindsight restarts so for example when a sandbox is configured with a ticker_interval of 60s, the timer_events are always triggered when second is 0.
I think this could be done by configuring a date on which timer_events should be aligned.

What do you think?

**Comment by trink** [comment]
I would be a -1 on that.  timer_events are typically expensive and to have them all fire at once is less than ideal.

**Comment by bbinet** [comment]
Would you accept a pull request if I make it configurable and keep the current behavior as the default, and that the documentation warn explicitly the users that synchronizing the timer_events are typically expensive and it should be turned on only for testing purpose?

Or could you think of any alternative way for testing sandboxes easily?

**Comment by trink** [comment]
No, I wouldn't integrate a PR like that into the main branch.

I use hindsight_cli for plugin testing with a static setup (no dynamic loading). I have a test directory with the proper structure and input data.  When the input is finished a cascading shutdown is automatically initiated and I verify the output(s).

**Comment by bbinet** [comment]
Ok, so the input data is stored in files? What about testing input sandboxes that receives data from udp?

Also, it may be worth documenting the use of hindsight_cli?

**Comment by trink** [comment]
Yeah, currently hindsight_cli is used for running reports (so an input that has and end).  For your UDP test case you would have to do a little shell scripting and shut it down manually if you don't want to alter the plugin.
