### ISSUE TITLE
Add a hs-cat program (equivalent to heka-cat)

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#18]
In https://github.com/mozilla-services/heka/issues/1329#issuecomment-141460206 you said you were experimenting with a new `hs-cat` program which was 6x faster than `heka-cat`.

**Comment by trink** [comment]
I don't know about equivalent. There has been some discussion about enabling it to run plugins and I am sorting out if something like this would be a viable test harness (for analysis and output plugins it is interesting but it may require as much setup as Hindsight itself; failing on the simple front).

**Comment by trink** [comment]
Linux only at the moment but here is what I am using:
https://github.com/mozilla-services/lua_sandbox/commit/11b56661b2c878f8f9959a7ec8955ca08a3d9d07
