### ISSUE TITLE
allow flexible configuration of buffering in Hindsight

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#22]
Heka has a few configuration settings to control buffering:
http://hekad.readthedocs.org/en/v0.10.0b1/buffering.html#buffering-configuration-settings

It would be great to see similar configuration supported in Hindsight (for now Hindsight allows to configure `output_path` and `output_size` values: https://github.com/trink/hindsight/blob/master/docs/configuration.md#configuration-variables )

In addition to Heka's allowed values for the `full_action` setting (`shutdown`, `drop`, `block`), we could imagine a new `drop_old` value which would drop the oldest messages in the queue (for example dropping the oldest output file) and advance the checkpoints accordingly.

What do you think?

**Comment by trink** [comment]
I would recommend monitoring actual disk space and correcting the problem or shutting down before it becomes a fatal issue, that is the best way to prevent data loss. As in #21 this functionality can be bolted on without having to change the infrastructure.  Issues or PR's to create these types of plugins are welcome and they would provide a lot more flexibility on how people can recover from errors.
