### ISSUE TITLE
pruning log files when some sandboxes are stopped

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#24]
When sandboxes are stopped either because of a failures or because we manually stop these sandboxes by creating `.off` files in the related load directory, the lines related to the stopped sandboxes in the `hindsight.cp` checkpoint file are not purged, and then the `prune_input.lua` input sandbox cannot prune the hindsight log files anymore.
Is it an expected behaviour?
How would you manage this use case of purging the log files when some sandboxes have been stopped?

**Comment by trink** [comment]
Yeah, before dynamic loading was added the only stoppage would be a failure (in most cases you would want the checkpoint to be preserved so you could fix the plugin and resume where you left off).
I still believe that should be the default for the failure case.  For the manually stopped case I agree the checkpoint should be deleted.

**Comment by bbinet** [comment]
I think you don't always want the checkpoint to be preserved so you could fix the plugin and resume where you left off: for some real time use cases, processing old data does not make sense as the data could be considered as out-of-date or obsolete when older then X seconds.

For my own use case, it does not make sense to preserve the checkpoint even in the case of a failure because the input data is aggregated in an analysis plugin which trigger new aggregated messages every ticker_interval (for example every minute), so if this analysis plugin dies because of a failure and then I fix and restart it, I don't want it to aggregate all the missed data in a single aggregated message which would not make sense.

So it would be great if preserving the checkpoint in case of failure could be configurable.

**Comment by trink** [comment]
For the real time use case suggested above this could be even worse (if the checkpoint is not present it will restart from the beginning of whatever is in the queue which could be even further back from where you were depending on the state/pruning of the other plugins). It really sounds like you want an option to disable the output plugin checkpointing (turn off the delivery guarantee) all together and just have the read start with the most current data (not caring if you skip some).

**Comment by trink** [comment]
Also, I don't understand your comment about the analysis plugin.  The checkpointing is per analysis thread and not per analysis plugin.  If your analysis plugin dies or is turned off or even if none are running the analysis thread will continue to advance the checkpoint as it consumes the input queue.

**Comment by bbinet** [comment]
Ok, I thought that if the checkpoint was not present it will be updated to
the latest message available in the queue, but I was wrong.
So it also means that when we load a new output sandbox dynamically (by
pushing the files in the "load/output" directory), the new output sandbox
will automatically process all the historical data which can be big if log
files are not pruned: this could make sense for some use case, but you may
also want it to process only new data.

Don't you think it should be configurable? For every new output sandbox, we
could imagine configuring whether its checkpoint should be set to the very
first or very last message in the queue.

Regarding the disabling of checkpointing all together, I think this is not
necessary if we can configure the checkpoint position (start or end of the
queue) of a new output sandbox. Delivery guarantee is a great feature of
Hindsight!

**Comment by bbinet** [comment]
Yes, you can ignore my comment about the analysis plugin, I thought it
would work the same way as the output plugins which was wrong.

**Comment by bbinet** [comment]
Would you agree if I split this issue in 2 separate distinct issues:

1. stopping a plugin should remove the corresponding line in the checkpoint file
2. allow to configure new output plugins so that their checkpoints are initialized at the end of the input/analysis queues

**Comment by trink** [comment]
For output plugins only:
1. I would clarify stopping as exiting NOT due to a Hindsight shutdown (on a shutdown the checkpoint should still be preserved)
i.e., `remove_checkpoint_on_stop = false/true` (defaulting to false, the current behaviour)
2. If no checkpoint exists
i.e.,  `initial_checkpoint = "oldest|newest"` (defaulting to oldest, the current behaviour)

Implementation wise there are a bunch of edge cases and race conditions

**Comment by bbinet** [comment]
Regarding a Hindsight shutdown, if we start Hindsight again, and a sandbox has been removed while Hindsight was down, I think it makes sense to also remove the corresponding line in the checkpoint file, isn't it?
(but I agree the checkpoint must be preserved for all remaining sandboxes)

**Comment by trink** [comment]
Yeah manually changing the internal state out from underneath HS (while running or stopped) are some of the edge cases I am talking about.  Basically if done incorrectly you get what you get (in most cases a process exit with error).  However in this case requiring a manual prune of the specific checkpoint while shutdown puts too much burden on the operator so we will have to strike the right balance.

**Comment by bbinet** [comment]
I'll close this issue as it has been split in 2 more specific issues: #29 and #30.
