### ISSUE TITLE
Don't panic if the 'analysis' dir is missing

### ISSUE THREAD

**Issue by mreid-moz** [trink/hindsight#26]
If it's valid to run with an empty 'analysis' dir, it should also be valid to run with no dir at all.

**Comment by trink** [comment]
This works as designed: The reason it is acceptable to run with nothing in the analysis directory is dynamic plugin loading.  The directory structure is verified on startup; if it is not there a panic level error is logged and the process exits.  

Technically if dynamic loading is disabled it could be allowed but special casing it at the moment doesn't seem worth it verses a fixed consistent layout.

**Comment by mreid-moz** [comment]
Can you just create it if it's not there?
