### ISSUE TITLE
add support ssl/tls encryption to hindsight heka_tcp.lua output plugin

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#27]
So that it can send data to a remote Heka instance which is configured with a TCP input with SSL/TLS.

**Comment by bbinet** [comment]
I may have some time next week to work on SSL support for the TCP input/output sandboxes: do you see any problem if I introduce a new dependency on the [Copas](https://github.com/keplerproject/copas) Lua library which seems to support SSL out of the box?

Also feel free to provide any guidance on the way you want this to be implemented.

**Comment by trink** [comment]
Hmm, that will pull in a couple of dependencies what you really need is just luasec. Since that is generally useful I wouldn't mind having it conditionally included if openssl is already installed.  You will have an easier time with integration if you use the LuaDist fork https://github.com/LuaDist/luasec

**Comment by bbinet** [comment]
Ok, thanks. I'll have a look and try to integrate with the luasec LuaDist fork.

**Comment by bbinet** [comment]
I've compiled a lua_sandbox with luasec (from the LuaDist fork), but when I try to `require "ssl"` from a lua input or output sandbox in Hindsight, I get an error "attempt to call a nil value".
```
[info] hindsight starting
[info] input_plugins starting: input.prune_input
[error] input.heka_tcp attempt to call a nil value
[error] input_plugins input.heka_tcp lsb_heka_create_input failed
[error] input_plugins input.heka_tcp create_inputs_plugin failed
[info] analysis_plugins starting input thread: 0
[info] analysis_plugins starting input thread: 1
[info] analysis_plugins starting input thread: 2
[info] analysis_plugins starting input thread: 3
[info] output_plugins starting: output.debug
[error] output.heka_tcp attempt to call a nil value
[error] output_plugins output.heka_tcp lsb_heka_create_output failed
[error] output_plugins output.heka_tcp create_output_plugin failed
```

But we don't get much information about what fails in the `require "ssl"` instruction: is there a way to configure Hindsight to show a lua stack trace or something similar to get more information on this error?

**Comment by bbinet** [comment]
Here is the luasandbox that I've compiled with luasec [luasandbox-0.15.3-Linux.tar.gz](https://github.com/trink/hindsight/files/177634/luasandbox-0.15.3-Linux.tar.gz).
The patch to build it was simply:
``` patch
diff --git a/cmake/externals.cmake b/cmake/externals.cmake
index a75cc02..8e110e3 100644
--- a/cmake/externals.cmake
+++ b/cmake/externals.cmake
@@ -113,6 +113,15 @@ add_dependencies(lua_socket ${LUA_PROJECT})
 # sandbox enhanced modules
 
 externalproject_add(
+    lua_sec
+    GIT_REPOSITORY https://github.com/LuaDist/luasec.git
+    GIT_TAG 329a8789f142bbbfef4fd7ed506285a25c3c0e0e
+    UPDATE_COMMAND ${CMAKE_COMMAND} -E copy ${CMAKE_CURRENT_LIST_DIR}/FindLua.cmake <SOURCE_DIR>/cmake
+    CMAKE_ARGS ${SANDBOX_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX=${EP_BASE}/io
+    INSTALL_ARGS ${INST_ARGS}
+)
+
+externalproject_add(
     lua_bloom_filter
     GIT_REPOSITORY https://github.com/mozilla-services/lua_bloom_filter.git
     GIT_TAG 255af01bc127fccbd11fc5e57218a5fcc8659c69
```

**Comment by bbinet** [comment]
I also tried to `require "ssl"` in a lua input/output sandbox using system lua-sec (by configuring hindsight.cfg to load from 
```
$ dpkg -l |grep lua-sec
ii  lua-sec:amd64             0.5-1                     amd64        SSL socket library for the Lua language
```

**Comment by trink** [comment]
I need to see the modifications you made to heka_tcp.lua also.

**Comment by bbinet** [comment]
For now I've commented out all my changes except the `require "ssl"` line, and it still causes the sandbox to collapse with the "attempt to call a nil value" error. Can you reproduce this error?

Here is the full `heka_tcp.lua` input sandbox that I'm using:
``` lua
-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at http://mozilla.org/MPL/2.0/.

--[[
Heka compatible TCP input

-- .cfg
filename = "heka_tcp.lua"
instruction_limit = 0

address = "127.0.0.1"
port    = 5565

--]]

require "coroutine"
local socket = require "socket"
require "heka_stream_reader"
require "string"
require "table"
------
-- local ssl_ctx = nil
-- local ssl_params = read_config("ssl_params") or nil
-- if ssl_params then
--     require "ssl"
--     ssl_ctx = assert(ssl.newcontext(ssl_params))
-- end
require "ssl"
------

local address = read_config("address") or "127.0.0.1"
local port = read_config("port") or 5565
local server = assert(socket.bind(address, port))
server:settimeout(0)
local threads = {}
local sockets = {server}

local function handle_client(client)
        cport = 0
    end

    local hsr = heka_stream_reader.new(
        string.format("%s:%d -> %s:%d", caddr, cport, address, port))
    client:settimeout(0)
    while client do
        local buf, err, partial = client:receive(need)
        if partial then buf = partial end
        if not buf then break end

        repeat
            found, consumed, need = hsr:find_message(buf)
            if found then inject_message(hsr) end
            buf = nil
        until not found

        if err == "closed" then break end

        coroutine.yield()
    end
end

function process_message()
    while true do
        local ready = socket.select(sockets, nil, 1)
        if ready then
            for _, s in ipairs(ready) do
                if s == server then
                    local client = s:accept()
                    if client then
                        -------
                        -- if ssl_ctx then
                        --     client = ssl.wrap(client, ssl_ctx)
                        --     client:dohandshake()
                        -- end
                        -------
                        sockets[#sockets + 1] = client
                        threads[client] = coroutine.create(
                            function() handle_client(client) end)
                    end
                else
                    if threads[s] then
                        local status = coroutine.resume(threads[s])
                        if not status then
                            s:close()
                            for i = #sockets, 2, -1 do
                                if s == sockets[i] then
                                    table.remove(sockets, i)
                                    break
                                end
                            end
                            threads[s] = nil
                        end
                    end
                end
            end
        end
    end
    return 0
end
```

**Comment by trink** [comment]
Looking at the code the problem is the first line of ssl.lua https://github.com/LuaDist/luasec/blob/master/src/ssl.lua#L7.  That is not supported in the sandbox.

**Comment by bbinet** [comment]
Thanks!
It seems it was already fixed in upstream brunoos luasec repository: https://github.com/brunoos/luasec/pull/23

I will try to propose the same fix for the LuaDist fork.

**Comment by bbinet** [comment]
Oh, I've just noticed you've edited your comment: does it mean the lua_sandbox could be updated to support the `module("ssl", package.seeall)` line?

**Comment by trink** [comment]
It is a relatively minor change that won't hurt anything and give us compatibility with some older modules so I could be persuaded if an issue appeared.

**Comment by bbinet** [comment]
Ok thanks, so I'll wait until the lua_sandbox supports this instruction.

**Comment by trink** [comment]
https://github.com/mozilla-services/lua_sandbox/commit/88a1b75b8ea52481596d5f88da5588d91db844f1

**Comment by bbinet** [comment]
It now works correctly.
I'll send a pull request soon to add support for SSL/TLS in heka_tcp input/output sandboxes.

**Comment by bbinet** [comment]
Here is the related pull request: https://github.com/mozilla-services/lua_sandbox/pull/124
