### ISSUE TITLE
build master hindsight error

### ISSUE THREAD

**Issue by tianlin** [trink/hindsight#28]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBRT_LIBRARY
    linked by target "hindsight" in directory /Users/tyrionlin/opensource/hindsight/src
    linked by target "hindsight_cli" in directory /Users/tyrionlin/opensource/hindsight/src
    linked by target "test_config" in directory /Users/tyrionlin/opensource/hindsight/src/test

**Comment by qzj1103** [comment]
I also get this problem . where is the CMake files?
