### ISSUE TITLE
analysis sandbox inject_message: Can't set message Hostname

### ISSUE THREAD

**Issue by bbinet** [trink/hindsight#34]
I know this is the expected behavior as described in the documentation: https://github.com/mozilla-services/lua_sandbox/blob/master/docs/heka/analysis.md#inject_message but what is the reasoning behind preventing the sandbox to override the message Hostname?

Here is my use case: I'm using an analysis sandbox to decorate messages going through the pipeline with new fields or reformat existing fields, so that these messages can then be forwarded to different output sandboxes but I do want to retain the original Hostname value of these messages.

So here is a simplified example of what I want to do in my analysis sandbox:

``` lua
function process_message()
    local msg = decode_message(read_message("raw"))
    -- [ add/remove/update some fields in msg.Fields ]
    inject_message(msg) -- the new injected message should keep the original msg.Hostname value
    return 0
end

function timer_event(ns)
end
```

Would it be possible to allow `Hostname` override in analysis sandbox `inject_message`?

**Comment by trink** [comment]
Analysis filters should be generating new content (data transformations should happen in the inputs/outputs).  If one is allowed to 'fixup' a message and make it look like it came from the original source this would be less than idea especially if untrusted code/users are allowed to perform dynamic analysis.

**Comment by bbinet** [comment]
Yes I could do it in the heka_tcp.lua input plugin, but I would prefer keep it clean.
If I use an analysis plugin, I can easily leverage the message_matcher config feature to filter the input messages that I want to decorate/modify rather than manually matching input messages directly in the heka_tcp.lua sandbox.
And if I have multiple input plugins which could create similar messages, I would have to copy the same code in every input plugins, whereas I could have done it once in the analysis plugin.

Also if it is a security consideration, when untrusted users are able to perform dynamic analysis, they are also able to load dynamic input/output plugins where they can rightfully "fixup" a message and mutate the hostname...

I would have thought that using analysis sandboxes for filtering or transforming flying messages was a sensible use case.

**Comment by trink** [comment]
- You can use modules,  the closest example I have is the decoder module here: https://github.com/mozilla-services/lua_sandbox/blob/master/sandboxes/heka/output/elasticsearch_bulk_api.lua#L38
- No, public access to dynamic loading will be sitting behind a web UI and input/output plugins will have different permissions (if allowed at all) than analysis plugins.
- It is a reasonable use case and you can... you just cannot make it look like it came from some other host after changing it :). I am not an absolute 'no' on the issue.  Since no message can actually be trusted this is probably a moot point.  I will leave the issue open... other comments/opinions welcome.

**Comment by bbinet** [comment]
Ok, I understand your reasoning.
Since my use case is a bit different, would you accept a patch to make the Logger/Hostname override configurable in the global hindsight.cfg file (and defaulting to the current behavior)?

**Comment by bbinet** [comment]
Finally I've decided to use a custom field to pass the original Hostname, and to update my output plugins to use it instead of the message Hostname.
It works and this workaround is ok with me, so I'm closing this issue.

**Comment by trink** [comment]
the analysis sandbox will take a cfg option to allow this: uses case implementing a Heka Go decoder sandbox.
The default will be to overwrite the Headers provided or not (the current behaviour)
The override will accept whatever the user provides (including nil)
