### ISSUE TITLE
Set remove_entries in a sandbox configuration

### ISSUE THREAD

**Issue by elemoine** [trink/hindsight#36]
I would like to set `remove_entries` in my sandbox' configuration file. It seems to me that this is not currently supported by Hindsight.

Would this addition be considered?

**Comment by trink** [comment]
Unlikely, since it would break the Heka Sandbox API. 
However, I am interested in your use case.  Will you provided more details of what you are trying to do and why?

**Comment by elemoine** [comment]
My use-case is simple: I need to configure a sandbox based on some environment variable.

So my plan was to get the environment variable from my sandbox' Lua code:

```lua
local os = require 'os'
local foo = os.getenv('FOO')
```

For this to work I need `os.getenv` to be available from the same box. So my plan was to set `remove_entries` in the sandbox' configuration file. Something like this:

```lua
remove_entries = {
  os = {'setlocale', 'execute'}    -- do not remove `getenv`
}
```

**Comment by trink** [comment]
For input/output plugins I would be fine with removing that restriction, but for analysis plugins the environment wouldn't be exposed (you would have to generate the cfg with variable in it)

**Comment by elemoine** [comment]
See https://github.com/mozilla-services/lua_sandbox/pull/138.

**Comment by trink** [comment]
closed i/o sandboxes now allow os.getenv() calls
