### ISSUE TITLE
The analysis process_message is not run

### ISSUE THREAD

**Issue by ugiwgh** [trink/hindsight#40]
I coding analysis lua like this
`local cnt=0
function process_message()
    cnt = cnt + 1
    return 0
end
function timer_event()
    inject_payload("cbuf", "CNTS", cnt)
end`
But the Payload is always 0, so the process_message function cannot runs.

**Comment by trink** [comment]
I would need to see the input plugin and config and the analysis plugin config (e.g. message matcher, ticker_interval).   Also you don't want to set the payload type to "cbuf" unless you are actually outputting a circular buffer.

**Comment by ugiwgh** [comment]
The analysis plugin config
 `ticker_interval = 1
filename = "ping.lua"
message_matcher = "TRUE"
thread = 0`

The input plugin
`local cnt=0
function process_message()
    cnt=cnt+1
    inject_message({Type="hello",
                    Fields={
                    {name="http_status" , value=200},
                    {name="request_size", value=1413, value_type=2, representation="B"}
                    }})
    return 0,tostring(cnt)
end
`

The input plugin config
`ticker_interval = 1
filename = "ping.lua"
preserve_data = true
`

**Comment by ugiwgh** [comment]
I deep into the code.  The hsi->fn isn't there. So I clear the output. It run ok.
